### ISSUE TITLE
terminator don't open sometimes

### ISSUE THREAD

**Issue by JAugusto42** [JAugusto42/terminator#1]
after installation you have to click the icon a few times until it opens. When execute from another terminal emulator:

Traceback (most recent call last):
  File "/usr/bin/terminator", line 85, in <module>
    from terminatorlib import ipc
  File "/usr/lib/python3.8/site-packages/terminatorlib/ipc.py", line 31, in <module>
    class DBusService(Borg, dbus.service.Object):
  File "/usr/lib/python3.8/site-packages/terminatorlib/ipc.py", line 62, in DBusService
    @dbus.service.method(BUS_NAME, in_signature='a{ss}')
  File "/usr/lib/python3.8/site-packages/dbus/decorators.py", line 157, in method
    validate_interface_name(dbus_interface)
ValueError: Invalid interface or error name 'net.tenshu.Terminator2-0xf1afa64690fe403': contains invalid character '-'

**Comment by JAugusto42** [comment]
i can replicate this on gnome.

**Comment by JAugusto42** [comment]
Apparently fixed by commit #12f186b
