### ISSUE TITLE
When we close a terminal a lot of error messages are showing.

### ISSUE THREAD

**Issue by JAugusto42** [JAugusto42/terminator#2]
First thats a lot of this error:
(terminator:7343): Gtk-CRITICAL **: 14:55:46.810: gtk_bin_remove: assertion 'priv->child == child' failed

then we have a python traceback

Traceback (most recent call last):
  File "/home/jaugusto/Projects/personal/terminator/terminatorlib/window.py", line 452, in closeterm
    Container.closeterm(self, widget)
  File "/home/jaugusto/Projects/personal/terminator/terminatorlib/container.py", line 116, in closeterm
    if self.get_property('term_zoomed'):
RecursionError: maximum recursion depth exceeded

**Comment by JAugusto42** [comment]
when we try to clone a widget, we dont referer what widget, so recursion limit exceede because terminator try to close something, but not knowing what.
